pipeline {
    agent any
    tools {
        maven 'maven-3.8'
    }
    environment {
        DOCKER_REPO_SERVER = '270278216475.dkr.ecr.ap-south-1.amazonaws.com'
        DOCKER_REPO = "${DOCKER_REPO_SERVER}/java-maven-app"
        APP_NAME = 'java-maven-app'
    }
    stages {
        stage('increment version') {
            steps {
                script {
                    echo 'incrementing app version...'
                    env.IMAGE_NAME = "v-${BUILD_NUMBER}"
                }
            }
        }
        stage('build app') {
            steps {
                script {
                    echo "building the application..."
                    sh 'mvn clean package'
                }
            }
        }
        stage('build and push image') {
            environment {
                AWS_ACCESS_KEY_ID = credentials('jenkins_aws_access_key_id')
                AWS_SECRET_ACCESS_KEY = credentials('jenkins_aws_secret_access_key')
            }
            steps {
                script {
                    echo "building the docker image..."
                    sh "docker build -t ${DOCKER_REPO}:${IMAGE_NAME} ."
                    
                    echo "Logging into AWS ECR..."
                    sh "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${DOCKER_REPO_SERVER}"
                    
                    echo "Pushing image to ECR..."
                    sh "docker push ${DOCKER_REPO}:${IMAGE_NAME}"
                }
            }
        }
        stage('deploy to EKS') {
            environment {
                AWS_ACCESS_KEY_ID = credentials('jenkins_aws_access_key_id')
                AWS_SECRET_ACCESS_KEY = credentials('jenkins_aws_secret_access_key')
            }
            steps {
                script {
                    echo 'Updating Kubeconfig for EKS Cluster...'
                    sh "aws eks update-kubeconfig --name k8s-demo-cluster --region ap-south-1"
                    
                    echo 'Deploying to Kubernetes using envsubst...'
                    sh 'envsubst < kubernetes/deployment.yaml | kubectl apply -f -'
                    sh 'envsubst < kubernetes/service.yaml | kubectl apply -f -'
                }
            }
        }
    }
}
