// Shared library ko top par import karo
@Library('my-shared-library') _  

pipeline {
    agent any
    
    tools {
        // Tumne bilkul sahi pakda tha, 'maven-3.8' hi naam hai tool ka
        maven 'maven-3.8' 
    }
    stages {
        stage('Step 0: Test Shared Library') {
            steps {
                // Direct custom function call from vars/sayHello.groovy
                sayHello('Dhruv Gupta') 
            }
        }
        
        stage('Step 1: Build App via Shared Library') {
            steps {
                // Direct custom function call from vars/buildJar.groovy
                buildJar() 
            }
        }
    }
}
