apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
    app: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: 270278216475.dkr.ecr.ap-south-1.amazonaws.com/java-maven-app:$IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
